name: Deploy to VPS

on:
  push:
    branches:
      - aster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy backend
      run: |
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/backend && git pull origin master"
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/backend/JobAggregator.Api && dotnet build && sudo systemctl restart JobAggregator"

    - name: Deploy frontend
      run: |
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/frontend && git pull origin master"
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/frontend && npm install && npm run build"
