name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add VPS to known_hosts
      run: |
        ssh-keyscan -H 194.99.20.210 >> ~/.ssh/known_hosts

    - name: Force Pull from Git
      run: |
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/ && git fetch origin master && git reset --hard origin/master"

    - name: Deploy backend and apply migrations
      run: |
        ssh deploy@194.99.20.210 "
          source ~/.profile
          export PATH=\$PATH:\$HOME/.dotnet/tools
          export ASPNETCORE_ENVIRONMENT=Production
          cd /var/www/JobAggregator/JobAggregator.Api/JobAggregator.Api &&
          dotnet build --configuration Release &&
          dotnet ef database update --configuration Release &&
          sudo systemctl restart jobaggregator
        "

    - name: Deploy frontend
      run: |
        ssh deploy@194.99.20.210 "cd /var/www/JobAggregator/jobaggregator.frontend && npm install && npm run build"
